apiVersion: apps/v1
kind: Deployment

metadata:
  name: learning-app
  namespace: deploy

spec:
  replicas: 3

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  minReadySeconds: 10

  selector:
    matchLabels:
      app: learning-app

  template:
    metadata:
      labels:
        app: learning-app

    spec:
      containers:
        - name: learning-app

          image: idven/learning-app:latest

          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /health
              port: 3000

            initialDelaySeconds: 5
            periodSeconds: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 3000

            initialDelaySeconds: 10
            periodSeconds: 5