apiVersion: v1
kind: ConfigMap
metadata:
  name: learning-app-config
  namespace: deploy
data:
  APP_PORT: "3000"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  ENABLE_FEATURE_X: "true"

  app-config.json: |
    {
      "maintenance_mode": false,
      "max_connections": 100
    }