replicaCount: 1

image:
  repository: idven/learning-app
  tag: v2
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30001

resources:
  requests:
    cpu: 100m
    memory: 64Mi

  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: false

env:
  NODE_ENV: production
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetMemoryUtilizationPercentage: 10
