apiVersion: v1
kind: Service
metadata:
  name: learning-app-service 
  namespace: deploy
spec:
  type: NodePort
  selector:
    app: learning-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001