apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: learning-app-hpa  
  namespace: deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: learning-app 
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1